apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aap-metrics-es
  namespace: ansible-automation-platform
  finalizers:
    - externalsecrets.external-secrets.io/externalsecret-cleanup
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: dev/aap/aap-metrics
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: token
      secretKey: token-key
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: aap-metrics-token