apiVersion: v1
kind: Secret
metadata:
  name: aap-metrics-token
  namespace: aap
type: Opaque
stringData:
  token: <token> # Create an AAP token with read scope (UI: your user → Tokens → add, scope read; in 2.5/2.6 it's under Access Management → Users) and store it next to AAP 


  # CLI Alternative: c -n aap create secret generic aap-metrics-token --from-literal=token=<AAP_TOKEN>