apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aap-metrics-service-monitor
  namespace: ansible-automation-platform
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: aap
  endpoints:
    - port: http
      path: /api/controller/v2/metrics/
      interval: 30s
      authorization:
        type: Bearer
        credentials:
          name: aap-metrics-token
          key: token-key